# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\rcode_executor\"\x82\x01\n\x0e\x45xecuteRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05\x12\r\n\x05input\x18\x05 \x03(\t\x12\x17\n\x0fmemory_limit_mb\x18\x06 \x01(\x05\"\xc1\x01\n\x0f\x45xecuteResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.code_executor.ExecutionStatus\x12\x0e\n\x06stdout\x18\x03 \x01(\t\x12\x0e\n\x06stderr\x18\x04 \x01(\t\x12\x16\n\x0ememory_used_kb\x18\x05 \x01(\x05\x12\x19\n\x11\x65xecution_time_ms\x18\x06 \x01(\x01\x12\x15\n\rerror_message\x18\x07 \x01(\t\"%\n\rStatusRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\"V\n\x0eStatusResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.code_executor.ExecutionStatus*\x81\x01\n\x0f\x45xecutionStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04\x12\x19\n\x15MEMORY_LIMIT_EXCEEDED\x10\x05\x12\x11\n\rRUNTIME_ERROR\x10\x06\x32\xa6\x01\n\x0c\x43odeExecutor\x12L\n\x0b\x45xecuteCode\x12\x1d.code_executor.ExecuteRequest\x1a\x1e.code_executor.ExecuteResponse\x12H\n\tGetStatus\x12\x1c.code_executor.StatusRequest\x1a\x1d.code_executor.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTIONSTATUS']._serialized_start=490
  _globals['_EXECUTIONSTATUS']._serialized_end=619
  _globals['_EXECUTEREQUEST']._serialized_start=34
  _globals['_EXECUTEREQUEST']._serialized_end=164
  _globals['_EXECUTERESPONSE']._serialized_start=167
  _globals['_EXECUTERESPONSE']._serialized_end=360
  _globals['_STATUSREQUEST']._serialized_start=362
  _globals['_STATUSREQUEST']._serialized_end=399
  _globals['_STATUSRESPONSE']._serialized_start=401
  _globals['_STATUSRESPONSE']._serialized_end=487
  _globals['_CODEEXECUTOR']._serialized_start=622
  _globals['_CODEEXECUTOR']._serialized_end=788
# @@protoc_insertion_point(module_scope)
