# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testcase_generator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'testcase_generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18testcase_generator.proto\x12\x12testcase_generator\"\xf5\x01\n\x17GenerateTestcaseRequest\x12\x0e\n\x06\x62oj_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11input_description\x18\x03 \x01(\t\x12\x1a\n\x12output_description\x18\x04 \x01(\t\x12\x17\n\x0fvalidation_code\x18\x05 \x01(\t\x12\x15\n\rsolution_code\x18\x06 \x01(\t\x12\x15\n\rnum_testcases\x18\x07 \x01(\x05\x12\x37\n\x11\x65xample_testcases\x18\x08 \x03(\x0b\x32\x1c.testcase_generator.Testcase\")\n\x08Testcase\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\"\x8b\x01\n\x18GenerateTestcaseResponse\x12\x0e\n\x06\x62oj_id\x18\x01 \x01(\x05\x12\x17\n\x0fvalidation_code\x18\x02 \x01(\t\x12\x15\n\rsolution_code\x18\x03 \x01(\t\x12/\n\ttestcases\x18\x04 \x03(\x0b\x32\x1c.testcase_generator.Testcase2\x83\x01\n\x11TestcaseGenerator\x12n\n\x11GenerateTestcases\x12+.testcase_generator.GenerateTestcaseRequest\x1a,.testcase_generator.GenerateTestcaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testcase_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATETESTCASEREQUEST']._serialized_start=49
  _globals['_GENERATETESTCASEREQUEST']._serialized_end=294
  _globals['_TESTCASE']._serialized_start=296
  _globals['_TESTCASE']._serialized_end=337
  _globals['_GENERATETESTCASERESPONSE']._serialized_start=340
  _globals['_GENERATETESTCASERESPONSE']._serialized_end=479
  _globals['_TESTCASEGENERATOR']._serialized_start=482
  _globals['_TESTCASEGENERATOR']._serialized_end=613
# @@protoc_insertion_point(module_scope)
